language: android
before_install:
- openssl aes-256-cbc -K $encrypted_66609a25f146_key -iv $encrypted_66609a25f146_iv
  -in keystore.jks.enc -out keystore.jks -d
- echo "sdk.dir=$ANDROID_HOME" > local.properties
- mkdir "$ANDROID_HOME/licenses" || true
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
- echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
- echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
android:
  components:
  - build-tools-26.0.1
  - android-26
  licenses:
  - android-sdk-license-.+
  - ".+"
install:
- true
script:
- "./gradlew assembleRelease --scan -s"
deploy:
  provider: releases
  api_key:
    secure: UGAyESQ6t4jQuX7AL7QapuCdn0BtnB/n9GIFVj3WYBe9RAEAMY2ofmjrpDvdTNgbabF035GBd6zxGIYW+3IHAaJpdddJzhys1qM29xgFV4utGjVQMsTgfX2Sdt+1RyLrDF/kz6WnqeL+UAybWWxtDjwICKlR00ddt3fjTab4R0PmyM5msdfAxMY1Apt9N/rNR7Y48Q7Mwg0fhX89fdZaub4da73KLMAmIxrFAQqzXeCj4bx9r9VrucwmU7XLvpaJerCAGQZJ9PjMhFlcQTdw2Fe2P5KGI6MLeEna2VJmz78PKcGd6wMZ1cnxqWbI8A/0sR5JdOrCBD+SkPJFjZ0sTEwhtDL6agnwG3MJOHYWseXcD56/uEqQ4GjYkUwhhEwdIedm1A5EsNrWI12a5Qk08cJQQOzAdsZxic8Jv1PRDO+48GIoSRGKFZmiJVoXzGS0LyHlcsucV+FLS0j+rC+pX0OI9vVER/UffSccmYk46d5ifqnUv2IOd8qzRzveIwn+f3SDKvXRnOQVgGAXbqr3GBiIxOI8iZiiwy5aOlYk2BTllOSHgh59Oy7aX2ZvfOPf1/qzF9utz47jEVUw72xNDs8Dqj9XL8j1CYEkR2gxxmBW4iNW3BP1SoXxf5NomdijwiSD8aHHWvX0zsl6Wt6Lt07DDxRNZY5k5N5SyGWkhsw=
  file_glob: true
  file: /home/travis/build/AlvaroChambi/ipsych/app/build/outputs/apk/release/*
  skip_cleanup: true
  on:
    tags: true
    branch: master
    repo: AlvaroChambi/tsproject
