language: android
dist: trusty
before_install:
- openssl aes-256-cbc -K $encrypted_4283994a9293_key -iv $encrypted_4283994a9293_iv
  -in keystore.jks.enc -out keystore.jks -d
- echo "sdk.dir=$ANDROID_HOME" > local.properties
- mkdir "$ANDROID_HOME/licenses" || true
- echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
- echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
- echo yes | sdkmanager "platforms;android-28"
- echo yes | sdkmanager "build-tools;28.0.3"
android:
  licenses:
  - android-sdk-preview-license-52d11cd2
  - android-sdk-license-.+
  - ".+"
script:
- "./gradlew testDebugUnitTest assembleRelease --scan -s"
deploy:
  provider: releases
  api_key:
    secure: "OzzFFBcjPkqu+R3y1imJPy8zcDBntdvGsKXTL4hCQUKyxbb2co4woF/Jj17Z3iXa1QDxc5Nv7vDYerGWFqxthSCJTZx0RSgXd71Z9J4KxA6CitbYn5urV7oXOOckLtMt2lf+QWfdZPk8FK0/9q1jFx5bsPrJ3x26VK5D8gyFTzQnqJ9pcDZLmEzayoh+avTtuEqWLkLBjq/Dpanp+WdybcVfmsy0teFUozgzi8ScaqWKAWUyVfbSCYppQn5fICU8nXFrYFBeCgMqj4PHih3uD3aT0KLz1FkJ4XzTaPFFHUvwi1UvFy1ARAkYcmeBOOPUeNatNeJvugD2UxYv1TLiOfFSJ6lHQH6yAFc/3e53ebNFdwFAfGXOWnXsLF8yEKO/dv+lN0tyw0CdngzrdYtiJKA3XEnn5e+EWezsf8+35NSn1CNtF2bxg52uNeE73LkyJ05wGMuIpfI6vOR4nq/4k00sH3+sfB+STOU8QgrMWK3l3iOF4GAsoipt3hYoQKXsL3N7ykAUjpGF4AZStm8jPpSBFb2pPh15qiEo7s4vRnFVEmUxitOkUxVhIsYwQhSk2/82aHp3acwf6DZQSBaa2Y+GmYkJbfUd4pfln6DvyCSRsM+1gva/2amk8GzIhYwWbp1eNL/C/BHX7JHV0eOgDPHTBWs6xC7EdlqOsZKsRuQ="
  file_glob: true
  file: "/home/travis/build/AlvaroChambi/tsproject/app/build/outputs/apk/release/*"
  skip_cleanup: true
  on:
    tags: true
    branch: master
    repo: AlvaroChambi/tsproject
env:
  global:
  - secure: anz2bx2VxHbrawC8L+RMQvSG/Xmr3H2AiYKmIJw4EuVdpXVqFIzoeC5nLLJP9bSidAg5ivGMe9lxvS3yVYhMGr54K4e7VEwD3FXZ49UfuGCugRSm8lAkUpIN7s0zmY/69hHzQo9g1kndOJIMowG4u6Dq9EccZEr62B0mSyeKAVTY3r7kSMGJGq9R3Eik4ZlT2mMF2HrThDHyVYRulowc7fIFhuqhhV0evisQbwQQCizIuV7gE8Iyl0RqungsJvk+YC3SON9I3vlcIN8Hzjq4Er7v3Mn+OsmmWKOVWlM7ioFPCrreLgpNNOwpa2uaMBR8C8N4nkFd5sINXnYybxX2MObdgup9fweKxVzPqsaMKrElq5G+4OnVCV4h3HIwESwoNXftpBSNQXcAtZqyBhxlOkFfMM9ASbKpxpsItcb+svUh5kdc2iqV9NC2sCaDZP2/mQRSzR6Od5af6rsLk+D/m0WzdCoL4/M3lzh20ngEQ7GdX9E12XKy/myyBp+MGaIKg0rHffUgLxiNQ/2pzMfhLVxVDjP0T30cIo/rG9eozq5/adZDKbUBoa041bbbX1up2jp/Y3r2MH/SBYEa+7/013F7MintZE0QqnYecTe4fZZe3Q+sk7GLt5nkkLD35yAWCMmeDzQRHrcdmjHRNsPpFFzDxJBVLSI8O/3QMJSFuuY=
  - secure: AJRWk21gUKX3fbcCW2ckOZTB4HTPkKOdeNj7bN3pIbzSf2RrGsNT1c67/sA5YzSIJmOQvrcNFGzGujqNF7a4vVKexKYKZEf6t88B3piDIuW5bdkxAMmK5ete2UvRA0AWE+9Paf+zKZfPCzS21wa+vTtQfEWQI2e0De9bbI9RM1S+XBemOxpw4zCVMjfSLd4m8FQzdfHIUzLUpKPzHDdneN7D3pChaVXVy3Lkv3ztIqmPPX9hlcV2hqMd8cYoFzZIM0da9FjQvA2+FGDcARZyg1R/ZLzEC7O9mhrhx8EQFl0LpEBiADnJ5weYHxOpr7rrcXV174LijCRt/vroPIySFBbJWs0ac+3nizZIixXxA3XomzgBIMTre1Ywy2HdLkyenY2wY843qDTnaOMzjh8DzLC23V37uDZmtEC7qpUuBqVewSnIkDXQFb3S+lJrdUMyJTkaIfJUIOS90TBpEAsHOGiXCE0fBPJsp9lvw5t3bmvwmBG90vRWwwivATz+Hd+Zc2E9GdmdVgJ8OYr0LBpYcsh5bZAR0+jzbO2SuKNLKFAv68wX+0a2kHRefY8wSUkUD/ZSv6mom9oGzTFMePwIXGnYUKvfBYIEdzLBt6i8xmOnL5y5p7hXmnqSqek0tBBEci83ZBWb4wP8eNPTifBAClfnH1GC34pyNZumNPe0xm0=
